name: Compile Action
on:
  workflow_dispatch:

permissions:
  contents: write
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
 
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: add permissions
        run: "git config --global --add safe.directory /__w/desmosPolygonalDiagrams/desmosPolygonalDiagrams"
      - name: set git variables
        run: |
            git config --global user.email "dmackinnon1@gmail.com"
            git config --global user.name "Dan MacKinnon"
      - name: cleanup old pdfs
        run: |
          git rm --ignore-unmatch *.pdf
          git commit --allow-empty -m 'removing old pdfs, github action'
          git push
      - name: Run LaTeX action
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          texlive_version: 2024
      - name: Store build timestamp
        run: echo "BUILD_TIME=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV
      - name: change file name
        run: "mv main.pdf main$BUILD_TIME.pdf"
      - name: adding new pdfs
        run: |
          git add main$BUILD_TIME.pdf
          git commit -m 'adding new pdfs, github action'
          git push
